/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package estoresearch;

import org.junit.Test;
import static org.junit.Assert.*;

public class BookTest {
    @Test 
    public void testBookConstructor() {
        /* declaring variables */
        String productID = "067192";
        String description = "Really Cool Book";
        double price = 2020.10;
        int year = 1050;
        String authors = "Pradhapan Rajendran";
        String publisher = "Cool Publishing Company";

        /* testing empty constructor */
        Book testBook = new Book();
        assertNotNull("testBook should be a created object with values from empty constructor", testBook);

        /* testing constructor */
        Book testBook2 = new Book(productID, description, price, year, authors, publisher);
        assertNotNull("testBook should be a created object with values from constructor", testBook);
    }

    @Test 
    public void testBookGetValues() {
        Book testBook = new Book("062195", "Nice Book", 20.00, 2020, "Pradhapan Rajendran", "Prad Publishing");

        /* checking if values are being retrieved properly from getter methods */
        assertTrue(testBook.getProductID().equals("062195"));
        assertTrue(testBook.getDescription().equals("Nice Book"));
        assertTrue(testBook.getPrice() == 20.00);
        assertTrue(testBook.getYear() == 2020);
        assertTrue(testBook.getAuthors().equals("Pradhapan Rajendran"));
        assertTrue(testBook.getPublisher().equals("Prad Publishing"));
    }

    @Test
    public void testBookSetValues() {
        Book testBook = new Book();

        /* setting class variables to values */
        testBook.setProductID("062195");
        testBook.setDescription("Nice Book");
        testBook.setPrice(20.00);
        testBook.setYear(2020);
        testBook.setAuthors("Pradhapan Rajendran");
        testBook.setPublisher("Prad Publishing");

        /* checking if variables were accessed and changed properly */
        assertTrue(testBook.getProductID().equals("062195"));
        assertTrue(testBook.getDescription().equals("Nice Book"));
        assertTrue(testBook.getPrice() == 20.00);
        assertTrue(testBook.getYear() == 2020);
        assertTrue(testBook.getAuthors().equals("Pradhapan Rajendran"));
        assertTrue(testBook.getPublisher().equals("Prad Publishing"));
    }
}
 