/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package estoresearch;

import org.junit.Test;
import static org.junit.Assert.*;

public class ProductTest {
    @Test 
    public void testProductConstructor() {
        /* declaring variables */
        String productID = "067192";
        String description = "Really Cool Product";
        double price = 2020.10;
        int year = 1050;

        /* testing empty constructor */
        Product testProduct = new Product();
        assertNotNull("testProduct should be a created object with values from empty constructor", testProduct);

        /* testing constructor */
        Product testProduct2 = new Product(productID, description, price, year);
        assertNotNull("testProduct should be a created object with values from constructor", testProduct2);
    }

    @Test 
    public void testProductGetValues() {
        Product testProduct = new Product("062195", "Nice Product", 20.00, 2020);

        /* checking if values are being retrieved properly from getter methods */
        assertTrue(testProduct.getProductID().equals("062195"));
        assertTrue(testProduct.getDescription().equals("Nice Product"));
        assertTrue(testProduct.getPrice() == 20.00);
        assertTrue(testProduct.getYear() == 2020);
    }

    @Test
    public void testProductSetValues() {
        Product testProduct = new Product();

        /* setting class variables to values */
        testProduct.setProductID("062195");
        testProduct.setDescription("Nice Product");
        testProduct.setPrice(20.00);
        testProduct.setYear(2020);

        /* checking if variables were accessed and changed properly */
        assertTrue(testProduct.getProductID().equals("062195"));
        assertTrue(testProduct.getDescription().equals("Nice Product"));
        assertTrue(testProduct.getPrice() == 20.00);
        assertTrue(testProduct.getYear() == 2020);
    }
}
 